import datetime
from pydantic import BaseModel, Field


class ConversationMessage(BaseModel):
    content: str = Field(description="response generated by the model")


class ConversationMessageResponse(ConversationMessage):
    references: list[str] = Field(description="list of input documents")
    question: str = Field(description="question asked")
    created_at: datetime.datetime = datetime.datetime.now()
